services:
  api:
    build:
      context: ./back
      dockerfile: src/Dockerfile
    container_name: pedala-api
    restart: on-failure:5
    environment:
      DB_URL: jdbc:sqlserver://pedaladb.database.windows.net:1433;database=pedaladatabase;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30
      DB_USER: pedalaadmin
      DB_PASSWORD: Admin123
      JWT_SECRET: pedala_secret_key_2024_production_very_long_secure_key_256bits
      PORT: 8080
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - pedala-uploads:/app/uploads

volumes:
  pedala-uploads:
